config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/" => "home#index"
  resources :todos
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  belongs_to :user
  validates :todo_text, presence: true
  validates :todo_text, length: { minimum: 2 }
  validates :due_date, presence: true

  def self.overdue
    where(" due_date< ?", Date.today).order(:due_date, :id)
  end

  def self.due_today
    where("due_date= ?", Date.today).order(:due_date, :id)
  end

  def self.due_later
    where("due_date> ?", Date.today).order(:due_date, :id)
  end

  def self.completed
    all.where(completed: true)
  end

  def self.incomplete
    all.where(completed: false)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :todos
  validates :firstname, presence: true
  validates :firstname, length: { minimum: 2 }
  validates :email, presence: true
  validates :email, :uniqueness => true
  validates :password, presence: true
  validates :password, length: { minimum: 8, maximum: 16 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_user_logged_in

  def ensure_user_logged_in
    unless current_user
      redirect_to "/"
    end
  end

  def current_user
    return @current_user if @current_user

    current_user_id = session[:current_user_id]
    if current_user_id
      @current_user = User.find(current_user_id)
    else
      nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    if current_user
      redirect_to todos_path
    else
      render "index"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def new
  end

  def create
    email = params[:email]
    user = User.find_by(email: email)
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      redirect_to "/"
    else
      flash[:error] = "your login attempt was invalid.Please retry."
      redirect_to new_sessions_path
    end
  end

  def destroy
    session[:current_user_id] = nil
    @current_user = nil
    redirect_to "/"
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = current_user.todos
    render "index"
  end

  def create
    todo_text = params[:todo_text]
    due_date = params[:due_date]
    todo_new = Todo.new(
      todo_text: todo_text,
      due_date: due_date,
      completed: false,
      user_id: current_user.id,
    )
    unless todo_new.save
      flash[:error] = todo_new.errors.full_messages.join(", ")
    end
    redirect_to todos_path
  end

  def update
    id = params[:id]
    completed = params[:completed]
    todo = current_user.todos.find(id)
    todo.completed = completed
    todo.save!
    redirect_to todos_path
  end

  def destroy
    id = params[:id]
    todo = current_user.todos.find(id)
    todo.destroy
    redirect_to todos_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_user_logged_in

  def index
    render "index"
  end

  def new
    render "new"
  end

  def create
    firstname = params[:first_name]
    lastname = params[:last_name]
    email = params[:email]
    password = params[:password]
    user = User.new(
      firstname: firstname,
      lastname: lastname,
      email: email,
      password: password,
    )
    if user.save
      session[:current_user_id] = user.id
      redirect_to "/"
    else
      flash[:error] = user.errors.full_messages.join(", ")
      redirect_to new_user_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class = "Home_title">
  <h2 >
    Welcome to the todo homepage
  </h2>
</div>
<div class="Home-authenticate">
  <p>
    If you are a new user,
    <%= link_to "Sign up here", new_user_path %>
  </p>
</div>
<div class="Home-authenticate">
  <p>
    If you are a new user,
    <%= link_to "Sign in here", new_sessions_path %>
  </p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wd201TodoManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%if @current_user%>
      <p class="UserHeader">
        Welcome
        <%= @current_user.firstname + " " +  @current_user.lastname%>
        <%= link_to "Sign-out", destroy_session_path , method: "delete" %> </p>
    </p>
  <%end%>
  <%if flash[:error]%>
    <p class="Flash-error"> <%= flash[:error] %></p>
  <%end%>
  <%= yield %>
</body>
</html>

app/views/todos/_todo-section.html.erb
<section class="TodoSection">
  <div class="TodoSectionTitle">
    <p class="TodoSectionTitle-text"><%=section_title%></p>
    <p class="TodoSectionTitle-remainingCount"><%= todos.completed.count %>/<%=todos.count%></p>
  </div>
  <ul>
    <% todos.each do |todo|%>
      <li class="TodoItem">
        <label class="TodoItem-container">
          <%= form_with(url: "/todos/#{todo.id}", method: "put") do %>
            <%= check_box_tag("completed", "isCompleted",todo.completed,
                                class: "TodoItem-checkbox",
                                onclick: "this.form.submit()",
                              ) 
             %>
          <%end%>
          <p class='<%= todo.completed ? "todocompleted" : ""%>'>
            <%= todo.todo_text%>
          </p>
          <% if show_due_date%>
            <p class="TodoItem-date">
              <%=todo.due_date.to_s(:short)%>
            </p>
          <%end%>
          <%= form_with(url: "/todos/#{todo.id}", method:"delete") do %>
            <%= image_submit_tag(  "folder_trash.png",
                                    class: 'TodoItem-image'
                                )
            %>
          <%end%>
        </label>
      </li>
    <%end%>
    <ul>
    </section>

app/views/todos/index.html.erb
<main class="TodoPageMain">
  <article>
    <h1 class="TodoPage-title">My To-do List</h1>
    <%= form_with(url: "/todos",method: "post",class: "AddTodo") do %>
      <%=text_field_tag "todo_text", nil,
                         autocomplete: "off",
                         required: true ,
                         autofocus: true,
                         placeholder: "What's next",
                         class: "AddTodo-text"
      %>
      <%=date_field_tag "due_date", nil,
                        required: true,
                        autocomplete: "off",
                        class: "AddTodo-date"
      %>
      <%=submit_tag  nil,
                     class: "AddTodo-button"
      %>
    <%end%>
    <%= render partial: "todo-section" , locals:
       {section_title: "Overdue",
        todos: @todos.overdue.incomplete,
        show_due_date: true,
       }%>
    <%= render partial: "todo-section" , locals:
       {section_title: "Due Today",
        todos: @todos.due_today,
        show_due_date: false,
       }%>
    <%= render partial: "todo-section" , locals:
       {section_title: "Due Later",
        todos: @todos.due_later,
        show_due_date: true,
       }%>
  </article>
</main>

app/views/users/new.html.erb
<h2 class="NewUsers-title">
  Welcome new user!
</h2>
<section class="UserNew">
  <%= form_with url: users_path do |form| %>
    <div class = "Form-section">
      <label class="FormInput-label"> First Name* </label>
      <%= form.text_field :first_name,
                          class: "Form-input",
                          autofocus: true,
                          required: true,
                          autocomplete: "off"
      %>
    </div>
    <div class = "Form-section">
      <label class="FormInput-label">
        Last Name
      </label>
      <%= form.text_field :last_name,
                          class: "Form-input",
                          autocomplete: "off"
      %>
    </div>
    <div class = "Form-section">
      <label class="FormInput-label">
        Email*
      </label>
      <%= form.email_field :email,
                           class: "Form-input",
                           required: true,
                           autocomplete: "off"
      %>
    </div>
    <div class = "Form-section">
      <label class="FormInput-label">
        Password*
      </label>
      <%= form.password_field :password,
                              class: "Form-input",
                              required: true,
                              autocomplete: "off"
      %>
    </div>
    <%= form.submit "Sign-up!",
                    class: "Form-submit"
    %>
  <% end %>
</section>